include:
  - project: 'internal/gitlab-ci'
    file: '/npm-based-ci.yml'

stages:
  - build
  - deploy

variables:
  NODE_VERSION: v20.10.0

build:
  stage: build
  tags:
    - main
  extends: .use-node
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  tags:
    - main
  extends: .use-backend-deploy
